spring:
   mail:
      host: smtp.google.com #发送邮件服务器
      username: xxx@google.com 
      password: justlovemaki #客户端授权码
      protocol: smtp #发送邮件协议
      properties.mail.smtp.auth: true
      properties.mail.smtp.port: 25 #端口号465或587
      default-encoding: utf-8
      from: xxx@google.com 
      smtp:
         connectiontimeout: 5000
         timeout: 3000
         writetimeout: 5000
pushjiang:
   sendurl: https://sc.ftqq.com/{$1}.send?text={$2}&desp={$3}
   sendkey: SCU7889Tbfca67411306777940e159006c2d02f39
            
logging:
   config: classpath:logback-spring.xml
